'1:'
findFlexure('flexure1.dat')
findFlexure('flexure11.dat')
'2:'
findFlexure('flexure2.dat')
findFlexure('flexure22.dat')
'3:'
findFlexure('flexure3.dat')
findFlexure('flexure33.dat')
'4:'
findFlexure('flexure4.dat')
findFlexure('flexure44.dat')
'5:'
findFlexure('flexure5.dat')
findFlexure('flexure55.dat')
'6:'
findFlexure('flexure6.dat')
findFlexure('flexure66.dat')
'7:'
findFlexure('flexure7.dat')
findFlexure('flexure77.dat')